name: React + Vite + TypeScript CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Lint code
        run: npm run lint

      - name: Type check and Build project
        run: npm run build

      - name: Run unit tests with Vitest
        run: npx vitest run --passWithNoTests

      - name: Upload build artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          # ทำให้ชื่อไม่ซ้ำกันในแต่ละ run
          name: github-pages-${{ github.run_id }}
          path: dist
